# Generated by Django 6.0.3 on 2026-03-28 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('emoji', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=200)),
                ('criteria', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firebase_uid', models.CharField(max_length=128, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('photo_url', models.URLField(blank=True)),
                ('green_credits', models.IntegerField(default=0)),
                ('rank', models.CharField(default='Seedling', max_length=50)),
                ('streak', models.IntegerField(default=0)),
                ('last_action_date', models.DateField(blank=True, null=True)),
                ('badges', models.JSONField(default=list)),
                ('total_actions', models.IntegerField(default=0)),
                ('trees_planted', models.IntegerField(default=0)),
                ('cleanups_done', models.IntegerField(default=0)),
                ('challenges_completed', models.IntegerField(default=0)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-green_credits'],
            },
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('challenge_type', models.CharField(choices=[('Open', 'Open'), ('Local', 'Local'), ('Corporate', 'Corporate'), ('Campus', 'Campus')], max_length=20)),
                ('action_type', models.CharField(choices=[('tree_planting', 'Tree Planting'), ('cleanup', 'Clean-up Drive'), ('upcycling', 'Upcycling / Repair'), ('transport', 'Sustainable Transport'), ('energy', 'Energy / Water Saving'), ('advocacy', 'Community Advocacy')], max_length=50)),
                ('target_count', models.IntegerField()),
                ('current_count', models.IntegerField(default=0)),
                ('location', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('badge_reward', models.CharField(max_length=50)),
                ('status', models.CharField(default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_challenges', to='greencredapp.userprofile')),
                ('participants', models.ManyToManyField(blank=True, related_name='joined_challenges', to='greencredapp.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('tree_planting', 'Tree Planting'), ('cleanup', 'Clean-up Drive'), ('upcycling', 'Upcycling / Repair'), ('transport', 'Sustainable Transport'), ('energy', 'Energy / Water Saving'), ('advocacy', 'Community Advocacy')], max_length=50)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='actions/')),
                ('image_url', models.URLField(blank=True)),
                ('credits_earned', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('liked_by', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='greencredapp.challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='greencredapp.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
