# Generated by Django 6.0.3 on 2026-03-28 13:20

import greencredapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greencredapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=greencredapp.models._get_image_storage, upload_to='greencred/actions/'),
        ),
    ]
